apiVersion: v1
kind: Service
metadata:
  name: posenet-service
  namespace: default
spec:
  selector:
    app: load-balancer
  type: NodePort
  ports:
    - port: 5000  # Service端口     
      NodePort: 32283  
      targetPort: 5000 # pod端口

